# Generated by Django 4.2.5 on 2023-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_rename_price_product_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
